// Token-tracking metadata: which models reason, which providers report
// reasoning/cached separately, and the canonical caveat copy used by the
// dashboard's (i) tooltips and inline alerts.

/** Substring patterns that identify reasoning-capable model families.
 *  Match is case-insensitive. Conservative — only families with documented
 *  reasoning behavior. False positives are worse than false negatives here:
 *  flagging a non-reasoning run as suspicious would be confusing. */
const REASONING_MODEL_PATTERNS: RegExp[] = [
  // OpenAI reasoning families
  /\bo1(?:-|$)/i,
  /\bo3(?:-|$)/i,
  /\bo4(?:-|$)/i,
  /\bgpt-5(?:\b|-|$)/i, // gpt-5, gpt-5.4, gpt-5-mini, gpt-5-pro
  // Anthropic extended-thinking variants
  /claude-3-7-sonnet/i,
  /claude-3\.7-sonnet/i,
  /claude-(?:opus|sonnet)-4/i,
  // Google Gemini "thinking" models
  /gemini-2\.5/i,
  /gemini-2-5/i,
  // DeepSeek reasoner
  /deepseek-(?:r1|reasoner)/i,
  // xAI reasoning preview
  /grok-(?:3|4)/i,
]

/** Returns true when the model string looks like a reasoning model. */
export function isReasoningModel(model: string | null | undefined): boolean {
  if (!model) return false
  return REASONING_MODEL_PATTERNS.some((re) => re.test(model))
}

/** Provider coverage table. Keys are user-facing provider labels; values are
 *  what we know LiteLLM normalizes today. Used to populate the (i) tooltip. */
export const TOKEN_PROVIDER_COVERAGE: Array<{
  provider: string
  reasoning: "yes" | "partial" | "no"
  cached: "yes" | "partial" | "no"
  notes?: string
}> = [
  {
    provider: "OpenAI (o1, o3, gpt-5 family)",
    reasoning: "yes",
    cached: "yes",
    notes: "Reasoning surfaces in `completion_tokens_details.reasoning_tokens`. Prompt cache hits via `prompt_tokens_details.cached_tokens`.",
  },
  {
    provider: "Anthropic (Claude 3.7 / 4.x with extended thinking)",
    reasoning: "yes",
    cached: "yes",
    notes: "LiteLLM maps `thinking` block tokens to reasoning_tokens, and `cache_read_input_tokens` to cached_tokens.",
  },
  {
    provider: "Google Gemini 2.5",
    reasoning: "yes",
    cached: "yes",
    notes: "LiteLLM normalizes `thoughts_token_count` and context-cache hits.",
  },
  {
    provider: "DeepSeek (deepseek-reasoner / R1)",
    reasoning: "yes",
    cached: "yes",
  },
  {
    provider: "xAI Grok",
    reasoning: "no",
    cached: "no",
    notes: "Reasoning tokens are not exposed by the provider API at this time.",
  },
  {
    provider: "AWS Bedrock / Vertex AI passthrough",
    reasoning: "partial",
    cached: "partial",
    notes: "Depends on the underlying model. Native Claude on Bedrock reports correctly; Titan / Llama variants typically don't.",
  },
  {
    provider: "Cohere, Mistral, others",
    reasoning: "no",
    cached: "partial",
    notes: "Top-level prompt/completion tokens are reported, but no breakdown.",
  },
]

/** The canonical caveat shown in the (i) tooltip on token stat cards. */
export const TOKEN_TRACKING_CAVEATS = {
  what: "Tokens are reported by the LLM provider for each call. Most providers split them into:",
  buckets: [
    { label: "Input", desc: "Prompt + system + tool definitions sent to the model." },
    {
      label: "Output (visible)",
      desc:
        "The model's text reply that's actually delivered to your code. For reasoning models, the provider's `completion_tokens` already INCLUDES reasoning — we subtract reasoning to show just the visible portion.",
    },
    {
      label: "Reasoning",
      desc:
        "Internal chain-of-thought tokens generated by reasoning models. Billed as output tokens by the provider.",
    },
    {
      label: "Cached",
      desc:
        "Prompt tokens that hit a provider-side cache and were charged at a discounted rate. Subset of input tokens.",
    },
  ],
  caveats: [
    "Coverage of the reasoning / cached buckets varies by provider. Models that don't expose this metadata show 0 in those columns even when reasoning may have happened internally.",
    "Streaming responses on some providers omit usage until the final chunk; if a run shows 0 across the board, the upstream call may have failed or been aborted.",
    "Token counts are best-effort from the provider — they're authoritative for billing, but the platform doesn't validate them against tokenizer-level counts.",
  ],
} as const
